services:
  mysql-db:
    image: mysql:8.0 # Specify MySQL version here
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - mysql-demo-data:/var/lib/mysql
    ports:
      - "3307:3306" # Expose MySQL on the default port

volumes:
  mysql-demo-data:
